language: ruby
rvm:
  - 2.2.0

sudo: false
cache: bundler

notifications:
  email: false

after_success:
  - ./deploy.sh

env:
  global:
    secure: "nXBPbyyGkvjrsmR01zVvCf6xVsgTA47twJbKwu5qMXqWQoEfU+1t6E5WoUBTmhV3OHAyqXRL8G387yXr1kk/Uf8jAwkpuH9HhaPKYjvAQM9+c2y54h+46vTKYjQsvoJm/tNd/gPS64Dk/juc/wOFPnDwxoNWXvdzQoicf33ZKLI="
    secure: "iCZdPf7FMWTcRj+JngOor7wEy16bsgRdnDf/l5Y5TLv2Nvwi03WNj1ViSOxqmXiMtZzWTQU67298uTz2zyG0NI1dUtXmsOZT3ya5MOg6eU19l/+JNSymoNkEdRHiTAvCJsHjkTsIMEVaQrWCV9ummnzgDBRtQDgWQnk6fR1XiyU="