language: ruby
rvm:
- 2.2.0
sudo: false
cache: bundler
notifications:
  email: false
after_success:
- bundle exec rake deploy
env:
  global:
  - secure: nGQ3/GEw9PcV5GMe1kGEWYfrqhNUqbe58Eslb+uZSSgax4RcdLyzyqJ90ieUzW4KwxPKkhsNpKKIuj9QSsaQOjl2YrUPGNU1pw9qbQWak4Nb56oF/pkKmphA76x0Ek3Vz2I7VD88xJGIgE+G+Rb2QWhGCWsmXW/3TtQYjxAynGw=
  - secure: qZYWG2PrR3mp6C0aorTXUv6EG7lWFJdVAi6VjJe2lKzWWtYKtWkzHS9Leg+2zxQY9T6NuEJN0T+31a5LjaKZzdl6/XXqaPMXblczJZ2Otn0QvgszhXd9WA+HtwxxOYvDnU4fdXtio+TH7l1FNnYhcO8iw5APnmpEVEUSIrMkTvw=
  - secure: KbotfC6nn+Ru7jipIHVuN5X4In7lR/Shyi7yv0WDRnXjYz3jqVFBeEzBbT7tLsIfprSfOmObkV+LtB/hp3EEwxFKc/srFzyiweh2EkzkQC2Huy9FicJQsigoAGRY0mNKJYLoz3H+VmyP4wDxDu1sG1x51z06iJpVldAE0UboJOs=
