language: ruby
rvm:
  - 2.2.0

sudo: false
cache: bundler

notifications:
  email: false

after_success:
  - ./deploy.sh

env:
  global:
    secure: "J+Ljq1gmEHK6uhMHYQJHjFR0iZS4WNy/P/Z5A9wNSqVgOKlhc/mUmdcI9ECoSUOWZx9L5Ed7VwR2drK/JN3nNzxf1WE6v/0+2j1FLsX2oMw2LMetb5N4KvwiwVv3uPuADRX2TvbiTTMandPB40wLPj6WEUd89Q1CBibBNn0Za6w="
    secure: "CljGej/PX+piuUku/x65ArfdxJQeIs5F25Fq8BWJKS9Vut9BHtwZWO1SPToVRY0kcoAsYE6TQ8r/Go06aWMpCUkSzs59lxelfJG3dqMb/vLQYsnRjnVpnBDbRI1WHX+CJLv1diwApiH+5TjWap+xeZKnjDoHzPix+k6BadS7ako="
