source 'https://rubygems.org'

gem 'sinatra',              '1.4.6'
gem 'sinatra-contrib',      '1.4.2'
gem 'puma',                 '2.9.0'
gem 'rake',                 '10.4.2'
gem 'json',                 '1.8.2'
gem 'unirest',              '1.1.2'
gem 'colorize',             '0.7.5'
gem 'sinatra-index',        github: 'mxlje/sinatra-index'
